img_1 = r'C:\Documets\Dron_way\test_img\img_1.png'
img_2 = r'C:\Documets\Dron_way\test_img\img_2.png'
img_3 = r'C:\Documets\Dron_way\test_img\img_3.png'
img_4 = r'C:\Documets\Dron_way\test_img\img_4.png'
img_5 = r'C:\Documets\Dron_way\test_img\img_5.png'
img_6 = r'C:\Documets\Dron_way\test_img\img_6.png'
img_7 = r'C:\Documets\Dron_way\test_img\img_7.png'
img_8 = r'C:\Documets\Dron_way\test_img\img_8.png'
